export const categories = {
    men: {
        clothes: ["outer", "top", "bottom", "homewear", "innerwear"],
        bags: [
            "crossbag",
            "waistbag",
            "totebag",
            "backpack",
            "shoulderbag",
            "laptopbag",
        ],
        shoes: [
            "sneakers",
            "loafers",
            "formal",
            "boots",
            "sandals",
            "accessories",
        ],
        accessories: [
            "wallets & card cases",
            "hats",
            "watches",
            "eyewear",
            "ties",
            "belts",
        ],
    },
    women: {
        clothes: [
            "top",
            "pants",
            "dresses",
            "skirts",
            "jumpsuits",
            "outer",
            "innerwear",
        ],
        bags: [
            "shoulderbag",
            "crossbag",
            "totebag",
            "eco & canvas bags",
            "backpack",
            "clutch",
            "pouch",
        ],
        shoes: [
            "flats & loafers",
            "boots",
            "pumps",
            "sandals",
            "slippers & mules",
            "sneakers",
        ],
        accessories: [
            "jewelry",
            "hats",
            "watches",
            "wallets & card cases",
            "eyewear",
            "belts",
        ],
    },
};
