const hardCodedProducts = [
    {
        sku: "12345ABC",
        name: "Sample Shirt",
        brand: "Brand A",
        gender: "Women",
        image: "http://example.com/image_shirt.jpg",
        category: { main: "의류", sub: "상의" },
        description: "This is a sample shirt description.",
        price: 29.99,
        stock: { S: 10, M: 20, L: 20 },
    },
    {
        sku: "67890DEF",
        name: "Sample Bag",
        brand: "Brand B",
        gender: "Women",
        image: "http://example.com/image_bag.jpg",
        category: { main: "가방", sub: "토트백" },
        description: "This is a sample bag description.",
        price: 49.99,
        stock: { S: 5, M: 15, L: 10 },
    },
    {
        sku: "11223XYZ",
        name: "Sample Shoes",
        brand: "Brand C",
        gender: "Women",
        image: "http://example.com/image_shoes.jpg",
        category: { main: "신발", sub: "부츠" },
        description: "This is a sample shoes description.",
        price: 79.99,
        stock: { 230: 5, 240: 10, 250: 5 },
    },
    {
        sku: "34567GHI",
        name: "Sample Dress",
        brand: "Brand D",
        gender: "Women",
        image: "http://example.com/image_dress.jpg",
        category: { main: "의류", sub: "원피스" },
        description: "This is a sample dress description.",
        price: 59.99,
        stock: { S: 8, M: 12, L: 5 },
    },
    {
        sku: "45678JKL",
        name: "Sample Skirt",
        brand: "Brand E",
        gender: "Women",
        image: "http://example.com/image_skirt.jpg",
        category: { main: "의류", sub: "스커트" },
        description: "This is a sample skirt description.",
        price: 39.99,
        stock: { S: 7, M: 14, L: 9 },
    },
    {
        sku: "56789MNO",
        name: "Sample Jacket",
        brand: "Brand F",
        gender: "Women",
        image: "http://example.com/image_jacket.jpg",
        category: { main: "의류", sub: "아우터" },
        description: "This is a sample jacket description.",
        price: 89.99,
        stock: { S: 4, M: 10, L: 6 },
    },
    {
        sku: "67890PQR",
        name: "Sample Sweater",
        brand: "Brand G",
        gender: "Women",
        image: "http://example.com/image_sweater.jpg",
        category: { main: "의류", sub: "상의" },
        description: "This is a sample sweater description.",
        price: 49.99,
        stock: { S: 12, M: 20, L: 18 },
    },
    {
        sku: "78901STU",
        name: "Sample Heels",
        brand: "Brand H",
        gender: "Women",
        image: "http://example.com/image_heels.jpg",
        category: { main: "신발", sub: "펌프스" },
        description: "This is a sample heels description.",
        price: 69.99,
        stock: { 230: 4, 240: 8, 250: 6 },
    },
    {
        sku: "89012VWX",
        name: "Sample Boots",
        brand: "Brand I",
        gender: "Women",
        image: "http://example.com/image_boots.jpg",
        category: { main: "신발", sub: "부츠" },
        description: "This is a sample boots description.",
        price: 99.99,
        stock: { 230: 3, 240: 7, 250: 5 },
    },
    {
        sku: "90123YZA",
        name: "Sample Sandals",
        brand: "Brand J",
        gender: "Women",
        image: "http://example.com/image_sandals.jpg",
        category: { main: "신발", sub: "샌들" },
        description: "This is a sample sandals description.",
        price: 29.99,
        stock: { 230: 6, 240: 11, 250: 3 },
    },
    {
        sku: "01234BCD",
        name: "Sample Backpack",
        brand: "Brand K",
        gender: "Women",
        image: "http://example.com/image_backpack.jpg",
        category: { main: "가방", sub: "백팩" },
        description: "This is a sample backpack description.",
        price: 69.99,
        stock: { S: 8, M: 16, L: 12 },
    },
    {
        sku: "12345EFG",
        name: "Sample Clutch",
        brand: "Brand L",
        gender: "Women",
        image: "http://example.com/image_clutch.jpg",
        category: { main: "가방", sub: "클러치" },
        description: "This is a sample clutch description.",
        price: 49.99,
        stock: { S: 5, M: 10, L: 5 },
    },
    {
        sku: "23456HIJ",
        name: "Sample Wallet",
        brand: "Brand M",
        gender: "Women",
        image: "http://example.com/image_wallet.jpg",
        category: { main: "액세서리", sub: "지갑" },
        description: "This is a sample wallet description.",
        price: 29.99,
        stock: { S: 20, M: 15, L: 10 },
    },
    {
        sku: "34567KLM",
        name: "Sample Hat",
        brand: "Brand N",
        gender: "Women",
        image: "http://example.com/image_hat.jpg",
        category: { main: "액세서리", sub: "모자" },
        description: "This is a sample hat description.",
        price: 19.99,
        stock: { S: 10, M: 20, L: 10 },
    },
    {
        sku: "45678NOP",
        name: "Sample Watch",
        brand: "Brand O",
        gender: "Women",
        image: "http://example.com/image_watch.jpg",
        category: { main: "액세서리", sub: "시계" },
        description: "This is a sample watch description.",
        price: 129.99,
        stock: { S: 5, M: 7, L: 8 },
    },
    {
        sku: "56789QRS",
        name: "Sample Sunglasses",
        brand: "Brand P",
        gender: "Women",
        image: "http://example.com/image_sunglasses.jpg",
        category: { main: "액세서리", sub: "아이웨어" },
        description: "This is a sample sunglasses description.",
        price: 59.99,
        stock: { S: 9, M: 12, L: 14 },
    },
    {
        sku: "67890TUV",
        name: "Sample Belt",
        brand: "Brand Q",
        gender: "Women",
        image: "http://example.com/image_belt.jpg",
        category: { main: "액세서리", sub: "벨트" },
        description: "This is a sample belt description.",
        price: 39.99,
        stock: { S: 10, M: 15, L: 20 },
    },
    {
        sku: "78901WXY",
        name: "Sample Scarf",
        brand: "Brand R",
        gender: "Women",
        image: "http://example.com/image_scarf.jpg",
        category: { main: "액세서리", sub: "스카프" },
        description: "This is a sample scarf description.",
        price: 19.99,
        stock: { S: 15, M: 10, L: 5 },
    },
    {
        sku: "89012ZAB",
        name: "Sample Blouse",
        brand: "Brand S",
        gender: "Women",
        image: "http://example.com/image_blouse.jpg",
        category: { main: "의류", sub: "상의" },
        description: "This is a sample blouse description.",
        price: 49.99,
        stock: { S: 12, M: 18, L: 15 },
    },
    {
        sku: "90123CDE",
        name: "Sample Coat",
        brand: "Brand T",
        gender: "Women",
        image: "http://example.com/image_coat.jpg",
        category: { main: "의류", sub: "아우터" },
        description: "This is a sample coat description.",
        price: 99.99,
        stock: { S: 6, M: 9, L: 8 },
    },
];
export default hardCodedProducts;
